version: '3.9'

services:
  restaurante:
    container_name: restaurante-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always
